Modified Certification Review section to clarify who does certification.  Created new file to maintain list of approvers.
lfn-cnti/certification pull request #134
Opened 2024-05-14 17:21 UTC by Smitholi67

Update to text in the Certification Review section. Added a new file to maintain list of approved certification reviewers.  The list is only temporarily populated with names.

## Pre-submission checklist:

Please check each of these after submitting your pull request:

- [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/cnf-certification/blob/main/Certified_CNF_Form.md)?
- [ ] Did you include the product/project logo in SVG, EPS or AI format?
- [ ] Does your logo clearly state the name of the product/project/org and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
- [ ] If your product/project is open source, did you include the repo_url?
- [ ] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

2024-05-14 19:06 UTC, lixuna approved these changes

2024-05-14 19:39 UTC, martin-mat requested changes

2024-05-14 19:39 UTC, martin-mat commented on ApprovedCertificationReviewers.md
> +| Martin Matyáš | [martin-at](https://github.com/martin-mat) | [Tietoevry](https://www.tietoevry.com/) |
missing 'm' [martin-mat]

2024-05-14 19:44 UTC, taylor commented on ApprovedCertificationReviewers.md
> +| Taylor Carpenter | [taylor](https://github.com/taylor) | [Vulk Coop](vulk.coop) |
```suggestion
| Taylor Carpenter | [taylor](https://github.com/taylor) | [Vulk Coop](vulk.coop) |
| Drew Bentley | [taylor](https://github.com/agentpoyo) | [Vulk Coop](vulk.coop) |
| Cédric Ollivier | [collivier](https://github.com/collivier) | [ Orange ](https://www.orange.com/) | 
```

2024-05-14 19:45 UTC, taylor commented on instructions.md
> +Reviews of certification pull requests are conducted by approved CNTi reviewers. Approved reviewers include CNTi co-chairs, project maintainers, and community members that have been selected by the c
```suggestion
Reviews of certification pull requests are conducted by approved CNTi reviewers. Approved reviewers include CNTi co-chairs, project maintainers, and community members that have been selected by the community or co-chairs.  A list of approved reviewers are maintained in ([this file ](https://github.com/lfn-cnti/certification/blob/main/CertificationReviewers.md)).  
```

2024-05-14 19:46 UTC, taylor commented on instructions.md
> +Reviews of certification pull requests are conducted by approved CNTi reviewers. Approved reviewers include CNTi co-chairs, project maintainers, and community members that have been selected by the c
I think a simpler name would cause less confusion.

2024-05-14 19:46 UTC, taylor commented on ApprovedCertificationReviewers.md
> +| Taylor Carpenter | [taylor](https://github.com/taylor) | [Vulk Coop](vulk.coop) |
I suggest renaming the file to be `CertificationReviewers.md`

2024-05-14 19:57 UTC, taylor approved these changes
lgtm

2024-05-14 19:57 UTC, merged

2024-05-15 14:06 UTC, rannyh commented
Now that the concept of "approved reviewers" is introduced, the question is how the list gets maintained? Who decides on adding/removing members? Should it be the project TSC/Co-chairs? I think it is worth clarifying @Smitholi67