Update instructions.md
lfn-cnti/certification pull request #139
Opened 2024-05-16 17:18 UTC by Smitholi67

Updated the Certification Instructions to include prereqs for participation.

Ref issues:  
https://github.com/lfn-cnti/certification/issues/131
https://github.com/lfn-cnti/certification/issues/138

2024-05-16 17:38 UTC, lixuna requested changes
please update URL for CNTi Terms

2024-05-16 17:38 UTC, lixuna commented on instructions.md
> +- Review the CNTi Participation Terms and Conditions (https://github.com/lfn-cnti/certification/blob/main/Certified_CNF_Terms.md)
```suggestion
- Review the CNTi Participation Terms and Conditions (https://github.com/lfn-cnti/certification/blob/main/Certified_CNTi_Terms.md)
```

2024-05-16 21:00 UTC, lixuna approved these changes

2024-05-17 16:38 UTC, lixuna approved these changes

2024-05-17 22:48 UTC, martin-mat requested changes
just nitpicking about "prereqs", other than that ok.

2024-05-17 22:48 UTC, martin-mat commented on instructions.md
> +## Participation Prereqs
This is a formal document. Don't abbreviate.
"Participation Prerequisites"

2024-05-17 22:48 UTC, martin-mat commented on instructions.md
> +## Technical Prereqs
Prerequisites

2024-05-21 18:13 UTC, lixuna approved these changes

2024-05-21 20:34 UTC, taylor approved these changes
lgtm

2024-05-21 20:49 UTC, merged